name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions-rs/toolchain@v1
        name: Setup Rust toolchain
        with:
          toolchain: stable

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - uses: actions-rs/cargo@v1
        with:
          command: check

  format:
    needs: check
    runs-on: ubuntu-latest

    steps:
      - uses: actions-rs/toolchain@v1
        name: Setup Rust toolchain
        with:
          toolchain: stable
          components: rustfmt

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

      - uses: actions-rs/cargo@v1
        if: failure()
        with:
          command: fmt

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: failure()
        with:
          commit_message: apply changes from rustfmt

  build:
    needs: check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
      fail-fast: false

    steps:
      - uses: actions-rs/toolchain@v1
        name: Setup Rust toolchain
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - uses: actions-rs/cargo@v1
        with:
          command: build

  clippy:
    needs: check
    runs-on: ubuntu-latest

    steps:
      - uses: actions-rs/toolchain@v1
        name: Setup Rust toolchain
        with:
          toolchain: stable
          components: clippy

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
    
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
