name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check syntax
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features

  format:
    needs: check
    runs-on: ubuntu-latest

    steps:
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check code format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

      - name: Auto-format code
        if: failure()
        uses: actions-rs/cargo@v1
        with:
          command: fmt

      - name: Commit auto-format changes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: failure()
        with:
          commit_message: apply changes from rustfmt

  build:
    needs: check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
      fail-fast: false

    steps:
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build project
        uses: actions-rs/cargo@v1
        with:
          command: build

  clippy:
    needs: check
    runs-on: ubuntu-latest

    steps:
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
    
      - name: Lint code with clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- --deny warnings
