name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        name: Setup Rust toolchain

      - uses: actions-rs/cargo@v1
        with:
          command: check

  format:
    needs: check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        name: Setup Rust toolchain
        with:
          components: fmt

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check

      - uses: actions-rs/cargo@v1
        if: failure()
        with:
          command: fmt

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: failure()
        with:
          commit_message: Apply changes from rustfmt

  build:
    needs: format
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        name: Setup Rust toolchain
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: build

  clippy:
    needs: format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        name: Setup Rust toolchain
        with:
          components: clippy
    
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
